#!/bin/sh

set -eu

if ! make format
then
    echo "There are some code style issues."
    echo "Run cargo fmt first."
    exit 1
fi

if ! make clippy
then
    echo "There are some clippy issues."
    exit 1
fi

if ! make test
then
    echo "There are some test issues."
    exit 1
fi

exit 0
