[workspace]

members = [
  "hifirs",
  "qobuz-client",
  "playlist-sync"
]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = 'abort'
debug = 1

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

