[env]
CARGO_MAKE_CLIPPY_ARGS = "--all-features -- -D warnings"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.test]
condition = { env = { CARGO_MAKE_CRATE_CURRENT_WORKSPACE_MEMBER = "qobuz-client" }}
