[package]
name = "playlist-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
qobuz-client = { version = "0.1.0", path = "../qobuz-client" }
rspotify = { version = "0.11", features = ["cli"] } 
tokio = { version = "1.0", features = ["full"]}
snafu = "0.7"
