[package]
edition = "2021"
name = "hifi-rs"
version = "0.2.3"
license-file = "../LICENSE"
repository = "https://github.com/iamdb/hifi.rs"

[dependencies]
async-broadcast = "0.5"
async-trait = "0.1"
bincode = "1.3"
byteorder = "1.4"
chrono = "0.4"
clap = { version = "4", features = ["derive", "env"] }
comfy-table = "7"
ctrlc = { version = "3.0", features = ["termination"] }
cursive = { version = "0.20", features = ["termion-backend", "markdown", "toml"] } 
dialoguer = { version = "0.10.1", features = ["fuzzy-select"] }
dirs = "5"
enum-as-inner = "0.6"
flume = "0.10"
futures = "0.3"
gstreamer = { version = "0.20", features = ["serde"] }
log = "0.4"
md5 = "0.7.0"
pretty_env_logger = "0.5"
hifirs-qobuz-api = { version = "0.1.0", path = "../qobuz-api" }
rand = "0.8"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.7"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls", "sqlite", "all-types", "offline" ] }
termion = "2"
textwrap = "0.16"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-tracy = { version = "0.10", features = ["broadcast", "only-localhost"] } 
ratatui = { version = "0.21", default-features = false, features = ["termion"] }
url = "2.2"
zbus = { version = "3", default-features = false, features = ["tokio"] }
