name: On Pull Request To Main
on:
  pull_request:
    paths:
      - '**.rs'
      - '**/Cargo.lock'
      - '**/Cargo.toml'
    branches:
      - main
env:
  CLICOLOR_FORCE: 1
jobs:
  pre-merge:
    name: Pre-merge checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    env:
      RUST_BACKTRACE: full
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ runner.os }}-rust-cache-${{ hashFiles('**/Cargo.lock') }}
    - name: Install gstreamer (ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools
    - name: Install gstreamer (macos-latest)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - name: Install cargo-make
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-make
        version: 0.36.4
    - name: Install cargo-insta
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-insta
        version: 1.26.0
    - name: Run CI Flow
      uses: actions-rs/cargo@v1
      env:
        QOBUZ_USERNAME: ${{secrets.QOBUZ_USERNAME}}
        QOBUZ_PASSWORD: ${{secrets.QOBUZ_PASSWORD}}
      with:
        command: make
        args: ci-flow
