name: On Pull Request To Main
on:
  pull_request:
    paths:
      - "**.rs"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
    branches:
      - main
env:
  CLICOLOR_FORCE: 1
jobs:
  pre-merge:
    name: Pre-merge checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}-rust-cache
      - name: Install gstreamer (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libunwind-dev libgstreamer1.0-dev
      - name: Install gstreamer (macos-latest)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install gstreamer 
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Install Cargo Plugins
        run: cargo install cargo-make cargo-insta sqlx-cli
      - name: Create db file
        run: "touch /tmp/data.db && cd hifirs && cargo sqlx database reset -y"
        env: 
          DATABASE_URL: "sqlite:///tmp/data.db"
      - name: Run CI Flow
        uses: actions-rs/cargo@v1
        env:
          QOBUZ_USERNAME: ${{secrets.QOBUZ_USERNAME}}
          QOBUZ_PASSWORD: ${{secrets.QOBUZ_PASSWORD}}
          DATABASE_URL: "sqlite:///tmp/data.db"
        with:
          command: make
          args: ci-flow
