name: On Pull Request To Main
on:
  pull_request:
    paths:
      - "**.rs"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - "**/package.json"
      - "**.svelte"
      - "**.js"
      - "**.ts"
    branches:
      - main
jobs:
  pre-merge:
    name: Pre-merge checks
    strategy:
      fail-fast: true
      matrix:
        arch: [x86_64, aarch64]
    runs-on: ubuntu-latest
    container:
      image: rust:1-bookworm
      env:
        PKG_CONFIG_PATH: /usr/lib/${{ matrix.arch }}-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.target }}-rust-cache
      - uses: extractions/setup-just@v1
      - name: Build player
        run: just build-player ${{ matrix.arch }}-unknown-linux-gnu
