name: On Pull Request To Main
on:
  pull_request:
    paths:
      - "**.rs"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
    branches:
      - main
env:
  CLICOLOR_FORCE: 1
jobs:
  pre-merge:
    name: Pre-merge checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}-rust-cache
      - name: Install gstreamer (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstrtspserver-1.0-dev libges-1.0-dev libncurses5-dev libncursesw5-dev
      - name: Install gstreamer (macos-latest)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Install Cargo Plugins
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make cargo-insta
      - name: Run CI Flow
        uses: actions-rs/cargo@v1
        env:
          QOBUZ_USERNAME: ${{secrets.QOBUZ_USERNAME}}
          QOBUZ_PASSWORD: ${{secrets.QOBUZ_PASSWORD}}
        with:
          command: make
          args: ci-flow
