name: Create release, build and upload artifacts

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*
env:
  CLICOLOR_FORCE: 1
jobs:
  create-build-upload:
    name: Build, package and publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.target }}-rust-cache
      - uses: extractions/setup-just@v1
      - name: Build player ${{ matrix.arch }} 
        run: just build-player ${{ matrix.arch }}-unknown-linux-gnu
      - name: Tar hifi-rs-${{ matrix.arch }}.tar.gz
        run: tar -cvf hifi-rs-${{ matrix.arch }}.tar.gz -C ./target/${{ matrix.arch }}/release/ hifi-rs
      - name: Release ${{ matrix.target }}
        uses: softprops/action-gh-release@v1
        with:
          files: hifi-rs-${{ matrix.arch }}.tar.gz
